[build]
  # This will be run the site build
  command = "npm run"
  # This is the directory is publishing to netlify's CDN
  $publish = "build"
  # functions build directory
  $functions = "functions-build"